version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: nginx.takap.dev
    ports:
      - "9000:80"
      - "9443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/html:/usr/share/nginx/html
  webapp:
    build:
      context: ./
      dockerfile: ./webapp/Dockerfile
    container_name: webapp
    ports:
      - "9001:9001"
    volumes:
      - ./webapp/app/:/app
    tty: true
  proxy:
    build:
      context: ./
      dockerfile: ./proxy/Dockerfile
    container_name: local_proxy
    ports:
      - "3128:3128"
    privileged: true
    command: /sbin/init
    tty: true